services:
  - type: web
    name: flask-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py

  - type: web
    name: streamlit-client
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/streamlit_app.py --server.port 10000